### PR TITLE
Fix build errors (plugin build on C++ UE 5.4.4 project; Android game build)

### PR DESCRIPTION
**Pull request by andreiagmu**
- Check `!= nullptr`, to fix plugin build error on C++ UE 5.4.4 project (Error c4706: assignment within conditional expression).
- Add #elif and #include, to fix Android game build error.
- Add `&` on types, to fix Android game build error.

### CODE REVIEW

**Review by StudioSyndiCatCaius — APPROVED** [review]

**Comment by StudioSyndiCatCaius** [comment]
Thanks for all your contributions!
